services:
  frontend-bpm:
    extends:
      file: ./frontend-bpm/compose.yaml  # adjust path to your project folder
      service: angular-prod
    image: frontend-bpm:prod
    container_name: frontend-bpm-prod
#    networks:
#      - app_network

  # backend-bpm:
  #   build: ./backend-bpm/compose.yaml
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - app_network

#networks:
#  app_network:
#    driver: bridge

# Shared volumes if needed
# volumes:
#   shared_data: