services:
  frontend:
    image: frontend-bpm-image
    container_name: frontend-bpm

    build:
      context: ./frontend-bpm
      dockerfile: Dockerfile
    ports:
      - "8080:8080"


  backend:
    image: backend-bpm-image
    container_name: backend-bpm
    build:
      context: ./backend-bpm
      dockerfile: Dockerfile 
    depends_on:
      db:
        condition: service_healthy
    # Links allow you to define extra aliases by which a service is reachable from another service. 
    # They are not required to enable services to communicate. 
    # By default, any service can reach any other service at that service's name. 
    links:
        - db:database


  db:
    image: postgres:12
    container_name: db-bpm
    # TODO: Use secrets management for production // use .env file
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    healthcheck:      
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  pgdata: {}