services:
  backend-bpm:
    container_name: backend-bpm
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:4000    
    depends_on:
      backend-bpm_db:
        condition: service_healthy    
    links: 
        - backend-bpm_db:db
  backend-bpm_db:
    container_name: backend-bpm_db
    image: postgis/postgis:12-3.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:      
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

  pgadmin_service:
    image: dpage/pgadmin4
    container_name: backend-bpm_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "15432:80"    # Keep port :80 inside container as per pgadmin official documentation
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      backend-bpm_db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata: {}
  pgadmin-data: {}

